[shell_alias]
update = "mise run update"

[tools]
prek = "0.5.3"
uv = "0.12.10"

[hooks]
postinstall = "prek install"

[tasks."update"]
description = "Update dependencies and regenerate lockfiles"
run = [
    "mise upgrade --local --bump",
    "mise lock",
    "prek install",
    "prek update --refresh",
    "prek run --all-files",
]
